version: '3.8'
#include:
#  - ../pgrsyslog-client/docker-compose.yaml
services:
  bash:
    image:           innovanon/bash-syslog
    container_name:  bash
    volumes:
      - acng:/mnt/acng:rw
      - aircaps:/mnt/aircaps:rw
      - airpsks:/mnt/airpsks:rw
      - bash-root:/root:rw
      #- bash-root:/mnt/bash-root:rw
      - ca-certs:/mnt/ca-certs:rw
      - ca-crl:/mnt/ca-crl:rw
      - ca-csr:/mnt/ca-csr:rw
      - ca-private:/mnt/ca-private:rw
      - ccache-etc:/mnt/ccache-etc:rw
      - ccache-redis:/mnt/ccache-redis:rw
      - dcc-kali:/mnt/dcc-kali:rw
      - dcc-ubuntu:/mnt/dcc-ubuntu:rw
      - dcc-voidlinux:/mnt/dcc-voidlinux:rw
      - git-keys:/mnt/git-keys:rw
      - git-repos:/mnt/git-repos:rw
      - import-db:/mnt/import-db:rw
      - msfrpcd:/mnt/msfrpcd:rw
      #- pgdata:/mnt/pgdata:rw
      - recond:/mnt/recond:rw
      - redis-certs:/mnt/redis-certs:rw
      - redis-data:/mnt/redis-data:rw
      - ../../mnt/test:/mnt/test:rw
      - slapd-certs:/mnt/slapd-certs:rw
      - slapd-root:/mnt/slapd-root:rw
      - syslog-client:/etc/rsyslog.d:ro
      - syslog-client:/mnt/syslog-client:rw
      - syslog-etc:/mnt/syslog-etc:rw
      - syslog-log:/mnt/syslog-log:rw
      - teamhack:/mnt/teamhack:rw
      - tor-etc:/mnt/tor-etc
      - vpn-c2-etc:/mnt/vpn-c2-etc:rw
      - vpn-s-etc:/mnt/vpn-s1-etc:rw
      - vpn-s-peer1:/mnt/vpn-s1-peer1:rw
      - wordlists:/mnt/wordlists:rw
    stdin_open: true
    tty:        true
    ports:
      - "0.0.0.0:4444:4444/tcp"

    restart:    no
    depends_on:
      syslog:
        condition:   service_started

volumes:
  bash-root:

