version: '3.8'
#include:
#  - ../pgrsyslog-client/docker-compose.yaml
services:
  bash:
    image:           innovanon/bash-syslog
    container_name:  bash
    volumes:
      - bash-root:/root:rw
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    depends_on:
      syslog:
        condition:   service_started

volumes:
  bash-root:

